# HSSFLDON - Data Preparation Notebook

This notebook will be used to prepare a public dataset to replicate the target environment for HSSFLDON. Primarily, this means a large but unlabeled dataset for the server and small labeled datasets for each client.

In [1]:
# Make sure all directories exist
import os
os.makedirs("test", exist_ok=True)
os.makedirs("server", exist_ok=True)
os.makedirs("clients", exist_ok=True)

In [2]:
# Load dataset from Hugging Face - https://huggingface.co/datasets/ucberkeley-dlab/measuring-hate-speech
from datasets import load_dataset
dataset = load_dataset("ucberkeley-dlab/measuring-hate-speech")

/Users/chrishinkson/Programming/COMP6970 - Federated Learning/HSSFLDON/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
# Split off test set to be used everywhere for evaluation
import pandas as pd
df = dataset["train"].to_pandas()
df.describe() #type: ignore

,comment_id,annotator_id,platform,sentiment,respect,insult,humiliate,status,dehumanize,violence,...,hatespeech,hate_speech_score,infitms,outfitms,annotator_severity,std_err,annotator_infitms,annotator_outfitms,hypothesis,annotator_age
count,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.00000,135556.000000,135556.000000,135556.000000,135556.000000,...,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135451.000000
mean,23530.416138,5567.097812,1.281352,2.954307,2.828875,2.56331,2.278638,2.698575,1.846211,1.052045,...,0.744733,-0.567428,1.034322,1.001052,-0.018817,0.300588,1.007158,1.011841,0.014589,37.910772
std,12387.194125,3230.508937,1.023542,1.231552,1.309548,1.38983,1.370876,0.898500,1.402372,1.345706,...,0.932260,2.380003,0.496867,0.791943,0.487261,0.236380,0.269876,0.675863,0.613006,11.641276
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-8.340000,0.100000,0.070000,-1.820000,0.020000,0.390000,0.280000,-1.578693,18.000000
25%,18148.000000,2719.000000,0.000000,2.000000,2.000000,2.00000,1.000000,2.000000,1.000000,0.000000,...,0.000000,-2.330000,0.710000,0.560000,-0.380000,0.030000,0.810000,0.670000,-0.341008,29.000000
50%,20052.000000,5602.500000,1.000000,3.000000,3.000000,3.00000,3.000000,3.000000,2.000000,0.000000,...,0.000000,-0.340000,0.960000,0.830000,-0.020000,0.340000,0.970000,0.850000,0.110405,35.000000
75%,32038.250000,8363.000000,2.000000,4.000000,4.000000,4.00000,3.000000,3.000000,3.000000,2.000000,...,2.000000,1.410000,1.300000,1.220000,0.350000,0.420000,1.170000,1.130000,0.449555,45.000000
max,50070.000000,11142.000000,3.000000,4.000000,4.000000,4.00000,4.000000,4.000000,4.000000,4.000000,...,2.000000,6.300000,5.900000,9.000000,1.360000,1.900000,2.010000,9.000000,0.987511,81.000000

In [4]:
# Print all possible columns in original dataset
print("Columns in original dataset:")
for column in df.columns: #type: ignore
    print(f"- {column}")

Columns in original dataset:
- comment_id
- annotator_id
- platform
- sentiment
- respect
- insult
- humiliate
- status
- dehumanize
- violence
- genocide
- attack_defend
- hatespeech
- hate_speech_score
- text
- infitms
- outfitms
- annotator_severity
- std_err
- annotator_infitms
- annotator_outfitms
- hypothesis
- target_race_asian
- target_race_black
- target_race_latinx
- target_race_middle_eastern
- target_race_native_american
- target_race_pacific_islander
- target_race_white
- target_race_other
- target_race
- target_religion_atheist
- target_religion_buddhist
- target_religion_christian
- target_religion_hindu
- target_religion_jewish
- target_religion_mormon
- target_religion_muslim
- target_religion_other
- target_religion
- target_origin_immigrant
- target_origin_migrant_worker
- target_origin_specific_country
- target_origin_undocumented
- target_origin_other
- target_origin
- target_gender_men
- target_gender_non_binary
- target_gender_transgender_men
- target_gender_transgender_unspecified
- target_gender_transgender_women
- target_gender_women
- target_gender_other
- target_gender
- target_sexuality_bisexual
- target_sexuality_gay
- target_sexuality_lesbian
- target_sexuality_straight
- target_sexuality_other
- target_sexuality
- target_age_children
- target_age_teenagers
- target_age_young_adults
- target_age_middle_aged
- target_age_seniors
- target_age_other
- target_age
- target_disability_physical
- target_disability_cognitive
- target_disability_neurological
- target_disability_visually_impaired
- target_disability_hearing_impaired
- target_disability_unspecific
- target_disability_other
- target_disability
- target_politics_alt_right
- target_politics_communist
- target_politics_conservative
- target_politics_democrat
- target_politics_green_party
- target_politics_leftist
- target_politics_liberal
- target_politics_libertarian
- target_politics_republican
- target_politics_socialist
- target_politics_other
- target_politics
- annotator_gender
- annotator_trans
- annotator_educ
- annotator_income
- annotator_ideology
- annotator_gender_men
- annotator_gender_women
- annotator_gender_non_binary
- annotator_gender_prefer_not_to_say
- annotator_gender_self_describe
- annotator_transgender
- annotator_cisgender
- annotator_transgender_prefer_not_to_say
- annotator_education_some_high_school
- annotator_education_high_school_grad
- annotator_education_some_college
- annotator_education_college_grad_aa
- annotator_education_college_grad_ba
- annotator_education_professional_degree
- annotator_education_masters
- annotator_education_phd
- annotator_income_<10k
- annotator_income_10k-50k
- annotator_income_50k-100k
- annotator_income_100k-200k
- annotator_income_>200k
- annotator_ideology_extremeley_conservative
- annotator_ideology_conservative
- annotator_ideology_slightly_conservative
- annotator_ideology_neutral
- annotator_ideology_slightly_liberal
- annotator_ideology_liberal
- annotator_ideology_extremeley_liberal
- annotator_ideology_no_opinion
- annotator_race_asian
- annotator_race_black
- annotator_race_latinx
- annotator_race_middle_eastern
- annotator_race_native_american
- annotator_race_pacific_islander
- annotator_race_white
- annotator_race_other
- annotator_age
- annotator_religion_atheist
- annotator_religion_buddhist
- annotator_religion_christian
- annotator_religion_hindu
- annotator_religion_jewish
- annotator_religion_mormon
- annotator_religion_muslim
- annotator_religion_nothing
- annotator_religion_other
- annotator_sexuality_bisexual
- annotator_sexuality_gay
- annotator_sexuality_straight
- annotator_sexuality_other

In [5]:
# Keep only certain columns
keep = ["text", "sentiment", "respect", "insult", "humiliate", "status", "dehumanize","violence", "genocide", "attack_defend", "hatespeech", "hate_speech_score"]
trimmedDf = df[keep].copy() #type: ignore
trimmedDf.describe()

,sentiment,respect,insult,humiliate,status,dehumanize,violence,genocide,attack_defend,hatespeech,hate_speech_score
count,135556.000000,135556.000000,135556.00000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000
mean,2.954307,2.828875,2.56331,2.278638,2.698575,1.846211,1.052045,0.678413,2.625992,0.744733,-0.567428
std,1.231552,1.309548,1.38983,1.370876,0.898500,1.402372,1.345706,1.179598,1.114960,0.932260,2.380003
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.340000
25%,2.000000,2.000000,2.00000,1.000000,2.000000,1.000000,0.000000,0.000000,2.000000,0.000000,-2.330000
50%,3.000000,3.000000,3.00000,3.000000,3.000000,2.000000,0.000000,0.000000,3.000000,0.000000,-0.340000
75%,4.000000,4.000000,4.00000,3.000000,3.000000,3.000000,2.000000,1.000000,3.000000,2.000000,1.410000
max,4.000000,4.000000,4.00000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,2.000000,6.300000

In [6]:
# Print final columns in trimmed dataset
print("Columns in trimmed dataset:")
for column in trimmedDf.columns:
    print(f"- {column}")

Columns in trimmed dataset:
- text
- sentiment
- respect
- insult
- humiliate
- status
- dehumanize
- violence
- genocide
- attack_defend
- hatespeech
- hate_speech_score

In [7]:
# Force GC for memory clearing of old dataframe
import gc
del dataset
del df
gc.collect()

45

In [8]:
# If one of the nine classification columns is above threshold, then it is considered part of target
classificationColumnThreshold = 2
classifications = ["respect", "insult", "humiliate", "status", "dehumanize","violence", "genocide", "attack_defend", "hatespeech"]

In [9]:
# Use above classification threshold to build textual target for each comment
def determineTarget(row) -> list[int]:

	# Shift all categories to binary true / false
	for column in classifications:
		if row[column] >= classificationColumnThreshold:
			row[column] = 1.0
		else:
			row[column] = 0.0

	# Create a multi-label vector for the target labels
	rowClassifications = [row[column] for column in classifications]
	return rowClassifications
	
trimmedDf["classifications"] = trimmedDf.apply(determineTarget, axis=1)
trimmedDf.describe()

,sentiment,respect,insult,humiliate,status,dehumanize,violence,genocide,attack_defend,hatespeech,hate_speech_score
count,135556.000000,135556.000000,135556.00000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000
mean,2.954307,2.828875,2.56331,2.278638,2.698575,1.846211,1.052045,0.678413,2.625992,0.744733,-0.567428
std,1.231552,1.309548,1.38983,1.370876,0.898500,1.402372,1.345706,1.179598,1.114960,0.932260,2.380003
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.340000
25%,2.000000,2.000000,2.00000,1.000000,2.000000,1.000000,0.000000,0.000000,2.000000,0.000000,-2.330000
50%,3.000000,3.000000,3.00000,3.000000,3.000000,2.000000,0.000000,0.000000,3.000000,0.000000,-0.340000
75%,4.000000,4.000000,4.00000,3.000000,3.000000,3.000000,2.000000,1.000000,3.000000,2.000000,1.410000
max,4.000000,4.000000,4.00000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,2.000000,6.300000

In [10]:
# Prep for stratifying by binning the hate_speech_score into 10 bins
trimmedDf["hate_speech_score_bin"] = pd.qcut(trimmedDf["hate_speech_score"], q=10, labels=False)
trimmedDf.describe()

,sentiment,respect,insult,humiliate,status,dehumanize,violence,genocide,attack_defend,hatespeech,hate_speech_score,hate_speech_score_bin
count,135556.000000,135556.000000,135556.00000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000
mean,2.954307,2.828875,2.56331,2.278638,2.698575,1.846211,1.052045,0.678413,2.625992,0.744733,-0.567428,4.490166
std,1.231552,1.309548,1.38983,1.370876,0.898500,1.402372,1.345706,1.179598,1.114960,0.932260,2.380003,2.864961
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.340000,0.000000
25%,2.000000,2.000000,2.00000,1.000000,2.000000,1.000000,0.000000,0.000000,2.000000,0.000000,-2.330000,2.000000
50%,3.000000,3.000000,3.00000,3.000000,3.000000,2.000000,0.000000,0.000000,3.000000,0.000000,-0.340000,4.000000
75%,4.000000,4.000000,4.00000,3.000000,3.000000,3.000000,2.000000,1.000000,3.000000,2.000000,1.410000,7.000000
max,4.000000,4.000000,4.00000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,2.000000,6.300000,9.000000

In [11]:
# Showcase sample before splitting
pd.set_option('display.max_colwidth', None)
print("Sample data point:")
print(trimmedDf.iloc[0])

Sample data point:
text                     Yes indeed. She sort of reminds me of the elder lady that played the part in the movie "Titanic" who was telling her story!!! And I wouldn't have wanted to cover who I really am!! I would be proud!!!! WE should be proud of our race no matter what it is!!
sentiment                                                                                                                                                                                                                                                                           0.0
respect                                                                                                                                                                                                                                                                             0.0
insult                                                                                                                                                                                                                                                                              0.0
humiliate                                                                                                                                                                                                                                                                           0.0
status                                                                                                                                                                                                                                                                              2.0
dehumanize                                                                                                                                                                                                                                                                          0.0
violence                                                                                                                                                                                                                                                                            0.0
genocide                                                                                                                                                                                                                                                                            0.0
attack_defend                                                                                                                                                                                                                                                                       0.0
hatespeech                                                                                                                                                                                                                                                                          0.0
hate_speech_score                                                                                                                                                                                                                                                                  -3.9
classifications                                                                                                                                                                                                                           [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
hate_speech_score_bin                                                                                                                                                                                                                                                                 1
Name: 0, dtype: object

In [12]:
# Split into train and test sets
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(trimmedDf, test_size=0.2, random_state=2002, stratify=trimmedDf["hate_speech_score_bin"])

In [13]:
# Save test to parquet for later use
df_test.to_parquet("test/test.parquet")

In [14]:
# From the train set, we want 70% for the server and 30% for clients
df_train_server, df_train_clients = train_test_split(df_train, test_size=0.3, random_state=2002, stratify=df_train["hate_speech_score_bin"])

In [15]:
# Save server
df_train_server.to_parquet("server/server.parquet")

In [16]:
# Check distribution and size of remaining dataset for clients
df_train_clients.describe()

,sentiment,respect,insult,humiliate,status,dehumanize,violence,genocide,attack_defend,hatespeech,hate_speech_score,hate_speech_score_bin
count,32534.000000,32534.000000,32534.000000,32534.000000,32534.000000,32534.000000,32534.000000,32534.000000,32534.000000,32534.000000,32534.000000,32534.000000
mean,2.955001,2.830270,2.566238,2.279062,2.695887,1.844870,1.055204,0.682302,2.624024,0.747065,-0.563835,4.490103
std,1.232783,1.309564,1.386277,1.369329,0.903670,1.400454,1.346186,1.179965,1.117385,0.933625,2.376253,2.864979
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.340000,0.000000
25%,2.000000,2.000000,2.000000,1.000000,2.000000,1.000000,0.000000,0.000000,2.000000,0.000000,-2.320000,2.000000
50%,3.000000,3.000000,3.000000,3.000000,3.000000,2.000000,1.000000,0.000000,3.000000,0.000000,-0.340000,4.000000
75%,4.000000,4.000000,4.000000,3.000000,3.000000,3.000000,2.000000,1.000000,3.000000,2.000000,1.410000,7.000000
max,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,2.000000,6.300000,9.000000

In [17]:
# Configure options for client splits
from math import floor
clientBiasStrength = 25
samplesPerClient = floor(len(df_train_clients) / 3)

In [18]:
# Map clients to specific targets for imbalance - this will be oracle network later on
clientMappings = {
    "Client_0": ["insult", "dehumanize", "violence"],
    "Client_1": ["genocide", "attack_defend", "respect"],
    "Client_2": ["sentiment", "humiliate", "hatespeech"]
}

In [19]:
# Create a copy so we don't mutate the original dataframe
availableForClientsDataframe = df_train_clients.copy()
clientDataframes = {}

In [20]:
# Split for each client
import numpy as np
for name, targets in clientMappings.items():

    # Calculate weights for the client based on data available
    is_target = availableForClientsDataframe[targets].sum(axis=1) > 0
    weights = np.where(is_target, clientBiasStrength, 1) 

    # Sample client data based on calculated weights
    client_sample = availableForClientsDataframe.sample(
        n=samplesPerClient, 
        weights=weights, 
        replace=True
    )
    
    # Store into separate dataframes
    clientDataframes[name] = client_sample
    
    # Remove from available so we don't double sample
    availableForClientsDataframe = availableForClientsDataframe.drop(client_sample.index)

print(f"Remaining 'noise' rows after splits: {len(availableForClientsDataframe)}")

Remaining 'noise' rows after splits: 7472

In [21]:
# Describe and save each client
for name, df in clientDataframes.items():
    print(f"--- {name} ---")
    print(df.describe())
    df.to_parquet(f"clients/{name}.parquet")

--- Client_0 ---
          sentiment       respect        insult     humiliate        status  \
count  10844.000000  10844.000000  10844.000000  10844.000000  10844.000000
mean       3.231741      3.135743      2.907599      2.597473      2.835024
std        0.977692      1.037087      1.096363      1.166170      0.887775
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        3.000000      2.000000      2.000000      2.000000      2.000000
50%        4.000000      3.000000      3.000000      3.000000      3.000000
75%        4.000000      4.000000      4.000000      4.000000      4.000000
max        4.000000      4.000000      4.000000      4.000000      4.000000

         dehumanize      violence      genocide  attack_defend    hatespeech  \
count  10844.000000  10844.000000  10844.000000   10844.000000  10844.000000
mean       2.122003      1.206842      0.773515       2.833272      0.859923
std        1.314916      1.371340      1.226974       0.980797      0.952734
min        0.000000      0.000000      0.000000       0.000000      0.000000
25%        1.000000      0.000000      0.000000       2.000000      0.000000
50%        2.000000      1.000000      0.000000       3.000000      0.000000
75%        3.000000      2.000000      1.000000       4.000000      2.000000
max        4.000000      4.000000      4.000000       4.000000      2.000000

       hate_speech_score  hate_speech_score_bin
count       10844.000000           10844.000000
mean           -0.055569               5.054316
std             2.063190               2.646170
min            -7.900000               0.000000
25%            -1.500000               3.000000
50%             0.120000               5.000000
75%             1.540000               7.000000
max             6.300000               9.000000
--- Client_1 ---
          sentiment       respect        insult     humiliate        status  \
count  10844.000000  10844.000000  10844.000000  10844.000000  10844.000000
mean       2.936924      2.823220      2.534674      2.242346      2.678901
std        1.217432      1.288436      1.400385      1.378519      0.889129
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        2.000000      2.000000      1.000000      1.000000      2.000000
50%        3.000000      3.000000      3.000000      2.000000      2.000000
75%        4.000000      4.000000      4.000000      3.000000      3.000000
max        4.000000      4.000000      4.000000      4.000000      4.000000

         dehumanize      violence      genocide  attack_defend    hatespeech  \
count  10844.000000  10844.000000  10844.000000   10844.000000  10844.000000
mean       1.810586      1.046016      0.673368       2.660365      0.742162
std        1.406069      1.352753      1.180597       1.038151      0.933414
min        0.000000      0.000000      0.000000       0.000000      0.000000
25%        1.000000      0.000000      0.000000       2.000000      0.000000
50%        2.000000      0.000000      0.000000       3.000000      0.000000
75%        3.000000      2.000000      1.000000       3.000000      2.000000
max        4.000000      4.000000      4.000000       4.000000      2.000000

       hate_speech_score  hate_speech_score_bin
count       10844.000000           10844.000000
mean           -0.584508               4.453246
std             2.360662               2.878705
min            -7.770000               0.000000
25%            -2.350000               2.000000
50%            -0.415000               4.000000
75%             1.390000               7.000000
max             4.870000               9.000000
--- Client_2 ---
          sentiment       respect        insult     humiliate        status  \
count  10844.000000  10844.000000  10844.000000  10844.000000  10844.000000
mean       3.104482      2.933143      2.649023      2.338713      2.721136
std        1.026200      1.216055      1.336157      1.326762      0.891552
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        2.750000      2.000000      2.000000      1.000000      2.000000
50%        3.000000      3.000000      3.000000      3.000000      3.000000
75%        4.000000      4.000000      4.000000      3.000000      3.000000
max        4.000000      4.000000      4.000000      4.000000      4.000000

         dehumanize      violence      genocide  attack_defend    hatespeech  \
count  10844.000000  10844.000000  10844.000000   10844.000000  10844.000000
mean       1.880948      1.065566      0.700572       2.669495      0.759498
std        1.377254      1.351127      1.201415       1.098046      0.935767
min        0.000000      0.000000      0.000000       0.000000      0.000000
25%        1.000000      0.000000      0.000000       2.000000      0.000000
50%        2.000000      1.000000      0.000000       3.000000      0.000000
75%        3.000000      2.000000      1.000000       4.000000      2.000000
max        4.000000      4.000000      4.000000       4.000000      2.000000

       hate_speech_score  hate_speech_score_bin
count       10844.000000           10844.000000
mean           -0.406054               4.618499
std             2.199374               2.755437
min            -8.050000               0.000000
25%            -2.020000               2.000000
50%            -0.270000               5.000000
75%             1.390000               7.000000
max             4.930000               9.000000